name: kakilima_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl_phone_field: ^3.1.0
  google_maps_flutter: ^2.5.3
  camera: ^0.11.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.0
  
  cupertino_icons: ^1.0.5
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/alfamart.png
    - assets/bank.png
    - assets/bca.png
    - assets/bri.png
    - assets/indomaret.png
    - assets/lawson.png
    - assets/logo_kakilima.png
    - assets/map_style.json
    - assets/mandiri.png
    - assets/maybank.png
    - assets/profile_image.jpg
    - assets/profil.jpg
    - assets/warteg_bahari1.jpg
    - assets/warteg_bahari2.jpg
    - assets/warteg_bahari3.jpg